-- MySQL Script generated by MySQL Workbench
-- Sat Jul 27 03:00:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vxcase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vxcase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS vxcase DEFAULT CHARACTER SET utf8 ;
USE vxcase ;

-- -----------------------------------------------------
-- Table vxcase.vendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS vxcase.vendas (
  ven_id INT NOT NULL AUTO_INCREMENT,
  ven_total FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (ven_id),
  UNIQUE INDEX ven_id_UNIQUE (ven_id ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table vxcase.produtos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS vxcase.produtos (
  pro_id INT NOT NULL AUTO_INCREMENT,
  pro_nome VARCHAR(70) NOT NULL,
  pro_preco FLOAT NOT NULL,
  pro_entrega INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (pro_id),
  UNIQUE INDEX pro_id_UNIQUE (pro_id ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table vxcase.vendas_produtos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS vxcase.vendas_produtos (
  ven_pro_id INT NOT NULL AUTO_INCREMENT,
  ven_id INT NOT NULL,
  pro_id INT NOT NULL,
  pro_preco FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (ven_pro_id),
  UNIQUE INDEX ven_pro_id_UNIQUE (ven_pro_id ASC),
  INDEX fk_vendas_produtos_vendas_idx (ven_id ASC),
  INDEX fk_vendas_produtos_produtos1_idx (pro_id ASC),
  CONSTRAINT fk_vendas_produtos_vendas
    FOREIGN KEY (ven_id)
    REFERENCES vxcase.vendas (ven_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_vendas_produtos_produtos1
    FOREIGN KEY (pro_id)
    REFERENCES vxcase.produtos (pro_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Capa VX Case Lilás Brilho iPod 5 (Envernizado)', 50.00, 5);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Capa Silicone iPhone XS MAX - Transparente', 140.00, 3);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Película VX Case Extreme iPhone XS Max - Brilhante', 150.00, 4);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Película Survivor Anti Impacto VX Case iPhone X - Preta', 170.00, 5);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Pelicula Traseira Anti Impacto iPhone XS Max - Brilhante', 120.00, 5);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Película da Câmera Anti Impacto VX Case iPhone XR - Prime', 35.00, 3);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Capa Envernizada VX Case Golden Paradise iPhone 7/8 Plus - Champagne', 140.00, 4);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Película Sticker iPhone 8 Plus - Branca', 100.00, 3);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Capa Emborrachada VX Case iPhone 7/8 Plus - Red', 140.00, 6);
insert into produtos (pro_nome, pro_preco, pro_entrega)
values ('Capa Carteira VX Case iPhone 7/8 Plus - Preta', 140.00, 7);